import { Roboto } from 'next/font/google'
import '@/app/_assets/scss/globals.scss'
import Header from '../_components/common/header/Header'
import Sidebar from '../_components/common/sidebar/Sidebar'

const roboto = Roboto({
  subsets: ['vietnamese'],
  weight: ['100', '300', '400', '500', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <div className='l-page'>
          <Header />
          <Sidebar />
          <main className='main-wrapper'>{children}</main>
        </div>
      </body>
    </html>
  )
}
