import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/common/header/Header";

const roboto = Roboto({ subsets: ["vietnamese"],
weight: [
  '100','300','400','500','700'
] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <Header/>
        {children}
      </body>
    </html>
  );
}
